name: Hourly Rebuild
on:
  schedule:
    - cron: '0 * * * *'  # Run every hour
  workflow_dispatch:      # Allow manual trigger

jobs:
  trigger-rebuild:
    runs-on: ubuntu-latest
    permissions:
      contents: write     # Needed for push access
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: main
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
          
      - name: Pull latest changes
        run: |
          git config --global pull.rebase true
          git pull --rebase origin main
          
      - name: Build site
        run: npm run build
          
      - name: Update timestamp
        run: |
          mkdir -p .github/timestamps
          echo "Last update: $(date -u)" > .github/timestamps/last-rebuild.txt
          
      - name: Commit and push if changed
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add .github/timestamps/last-rebuild.txt
          git commit -m "chore: trigger rebuild [skip ci]" || exit 0
          git push